=== anujch111991-eng/DemoRepo/src/main/resources/Testng.dtd
<!ELEMENT suite (listeners?, test)>
<!ATTLIST suite name CDATA #REQUIRED>
<!ATTLIST suite verbose NMTOKEN #REQUIRED>

<!ELEMENT listeners (listener+)>
<!ELEMENT listener EMPTY>
<!ATTLIST listener class-name CDATA #REQUIRED>

<!ELEMENT test (classes)>
<!ATTLIST test name CDATA #REQUIRED>

<!ELEMENT classes (class+)>

<!ELEMENT class EMPTY>
<!ATTLIST class name CDATA #REQUIRED>

=== anujch111991-eng/DemoRepo/src/main/resources/Testng.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE suite SYSTEM "Testng.dtd">

<suite name="Ventoux Dev Application Automation" verbose="1">

    <listeners>
        <listener class-name="com.qa.ExtentReportListener.ExtentReporterNG"/>
    </listeners>

    <test name="Dev Application">
        <classes>
        	<class name="com.ventoux.qa.test.HomePageChartsTitle_InfoIconText_TEST"/>
        	<class name="com.ventoux.qa.test.IdentityAppPortalTest"/>
        	<class name="com.ventoux.qa.test.IdentityLoginTest"/>
            <class name="com.ventoux.qa.test.TocSelectionPageTest"/>
        </classes>
    </test>

</suite>
